spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "https://lostfound-frontend-886354540707.asia-south1.run.app"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**,/auth/**
            - id: item-service
              uri: lb://ITEM-SERVICE
              predicates:
                - Path=/api/items/**
            - id: claim-service
              uri: lb://CLAIM-SERVICE
              predicates:
                - Path=/api/claims/**

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://10.10.0.10:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}